server:
  port: 9090  # Sets Spring Boot server port

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_db
    username: root
    password: root
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
